// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: im.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChannelType int32

const (
	ChannelType_CHANNEL_TYPE_UNSPECIFIED ChannelType = 0
	ChannelType_CHANNEL_TYPE_WORLD       ChannelType = 1
	ChannelType_CHANNEL_TYPE_ALLIANCE    ChannelType = 2
	ChannelType_CHANNEL_TYPE_ACTIVITY    ChannelType = 3
	ChannelType_CHANNEL_TYPE_PRIVATE     ChannelType = 4
	ChannelType_CHANNEL_TYPE_SYSTEM      ChannelType = 5
)

// Enum value maps for ChannelType.
var (
	ChannelType_name = map[int32]string{
		0: "CHANNEL_TYPE_UNSPECIFIED",
		1: "CHANNEL_TYPE_WORLD",
		2: "CHANNEL_TYPE_ALLIANCE",
		3: "CHANNEL_TYPE_ACTIVITY",
		4: "CHANNEL_TYPE_PRIVATE",
		5: "CHANNEL_TYPE_SYSTEM",
	}
	ChannelType_value = map[string]int32{
		"CHANNEL_TYPE_UNSPECIFIED": 0,
		"CHANNEL_TYPE_WORLD":       1,
		"CHANNEL_TYPE_ALLIANCE":    2,
		"CHANNEL_TYPE_ACTIVITY":    3,
		"CHANNEL_TYPE_PRIVATE":     4,
		"CHANNEL_TYPE_SYSTEM":      5,
	}
)

func (x ChannelType) Enum() *ChannelType {
	p := new(ChannelType)
	*p = x
	return p
}

func (x ChannelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelType) Descriptor() protoreflect.EnumDescriptor {
	return file_im_proto_enumTypes[0].Descriptor()
}

func (ChannelType) Type() protoreflect.EnumType {
	return &file_im_proto_enumTypes[0]
}

func (x ChannelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelType.Descriptor instead.
func (ChannelType) EnumDescriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{0}
}

type MsgType int32

const (
	MsgType_MSG_TYPE_UNSPECIFIED MsgType = 0
	MsgType_MSG_TYPE_TEXT        MsgType = 1
	MsgType_MSG_TYPE_IMAGE       MsgType = 2
	MsgType_MSG_TYPE_EMOJI       MsgType = 3
	MsgType_MSG_TYPE_SYSTEM      MsgType = 4
	MsgType_MSG_TYPE_LINK        MsgType = 5
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "MSG_TYPE_UNSPECIFIED",
		1: "MSG_TYPE_TEXT",
		2: "MSG_TYPE_IMAGE",
		3: "MSG_TYPE_EMOJI",
		4: "MSG_TYPE_SYSTEM",
		5: "MSG_TYPE_LINK",
	}
	MsgType_value = map[string]int32{
		"MSG_TYPE_UNSPECIFIED": 0,
		"MSG_TYPE_TEXT":        1,
		"MSG_TYPE_IMAGE":       2,
		"MSG_TYPE_EMOJI":       3,
		"MSG_TYPE_SYSTEM":      4,
		"MSG_TYPE_LINK":        5,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_im_proto_enumTypes[1].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_im_proto_enumTypes[1]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{1}
}

type SenderInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SenderId        int64                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderName      string                 `protobuf:"bytes,2,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	SenderHeadImage string                 `protobuf:"bytes,3,opt,name=sender_head_image,json=senderHeadImage,proto3" json:"sender_head_image,omitempty"`
	SenderRank      int32                  `protobuf:"varint,4,opt,name=sender_rank,json=senderRank,proto3" json:"sender_rank,omitempty"`
	AllianceName    string                 `protobuf:"bytes,5,opt,name=alliance_name,json=allianceName,proto3" json:"alliance_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SenderInfo) Reset() {
	*x = SenderInfo{}
	mi := &file_im_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SenderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderInfo) ProtoMessage() {}

func (x *SenderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderInfo.ProtoReflect.Descriptor instead.
func (*SenderInfo) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{0}
}

func (x *SenderInfo) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SenderInfo) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *SenderInfo) GetSenderHeadImage() string {
	if x != nil {
		return x.SenderHeadImage
	}
	return ""
}

func (x *SenderInfo) GetSenderRank() int32 {
	if x != nil {
		return x.SenderRank
	}
	return 0
}

func (x *SenderInfo) GetAllianceName() string {
	if x != nil {
		return x.AllianceName
	}
	return ""
}

type ImMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         int64                  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"` // Server-assigned, per-channel monotonic
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ChannelType   ChannelType            `protobuf:"varint,3,opt,name=channel_type,json=channelType,proto3,enum=im.v1.ChannelType" json:"channel_type,omitempty"`
	Sender        *SenderInfo            `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	MsgType       MsgType                `protobuf:"varint,6,opt,name=msg_type,json=msgType,proto3,enum=im.v1.MsgType" json:"msg_type,omitempty"`
	MsgParam      []string               `protobuf:"bytes,7,rep,name=msg_param,json=msgParam,proto3" json:"msg_param,omitempty"`            // Template vars for SYSTEM messages
	SendTime      int64                  `protobuf:"varint,8,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`           // Server receive time, unix ms
	ClientMsgId   string                 `protobuf:"bytes,9,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"` // Client-generated UUID for idempotency
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImMessage) Reset() {
	*x = ImMessage{}
	mi := &file_im_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImMessage) ProtoMessage() {}

func (x *ImMessage) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImMessage.ProtoReflect.Descriptor instead.
func (*ImMessage) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{1}
}

func (x *ImMessage) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *ImMessage) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ImMessage) GetChannelType() ChannelType {
	if x != nil {
		return x.ChannelType
	}
	return ChannelType_CHANNEL_TYPE_UNSPECIFIED
}

func (x *ImMessage) GetSender() *SenderInfo {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *ImMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ImMessage) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_MSG_TYPE_UNSPECIFIED
}

func (x *ImMessage) GetMsgParam() []string {
	if x != nil {
		return x.MsgParam
	}
	return nil
}

func (x *ImMessage) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *ImMessage) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

type AuthReq struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Token   string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Version string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Per-channel last seen msg_id for reconnect gap detection
	ChannelLastMsgIds map[string]int64 `protobuf:"bytes,3,rep,name=channel_last_msg_ids,json=channelLastMsgIds,proto3" json:"channel_last_msg_ids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthReq) Reset() {
	*x = AuthReq{}
	mi := &file_im_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReq) ProtoMessage() {}

func (x *AuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReq.ProtoReflect.Descriptor instead.
func (*AuthReq) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{2}
}

func (x *AuthReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AuthReq) GetChannelLastMsgIds() map[string]int64 {
	if x != nil {
		return x.ChannelLastMsgIds
	}
	return nil
}

type AuthResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Uid           int64                  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	ServerTime    int64                  `protobuf:"varint,4,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResp) Reset() {
	*x = AuthResp{}
	mi := &file_im_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResp) ProtoMessage() {}

func (x *AuthResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResp.ProtoReflect.Descriptor instead.
func (*AuthResp) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{3}
}

func (x *AuthResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AuthResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AuthResp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AuthResp) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type SendMsgReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ChannelType   ChannelType            `protobuf:"varint,2,opt,name=channel_type,json=channelType,proto3,enum=im.v1.ChannelType" json:"channel_type,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	MsgType       MsgType                `protobuf:"varint,4,opt,name=msg_type,json=msgType,proto3,enum=im.v1.MsgType" json:"msg_type,omitempty"`
	MsgParam      []string               `protobuf:"bytes,5,rep,name=msg_param,json=msgParam,proto3" json:"msg_param,omitempty"`
	ClientMsgId   string                 `protobuf:"bytes,6,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMsgReq) Reset() {
	*x = SendMsgReq{}
	mi := &file_im_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgReq) ProtoMessage() {}

func (x *SendMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgReq.ProtoReflect.Descriptor instead.
func (*SendMsgReq) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{4}
}

func (x *SendMsgReq) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *SendMsgReq) GetChannelType() ChannelType {
	if x != nil {
		return x.ChannelType
	}
	return ChannelType_CHANNEL_TYPE_UNSPECIFIED
}

func (x *SendMsgReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMsgReq) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_MSG_TYPE_UNSPECIFIED
}

func (x *SendMsgReq) GetMsgParam() []string {
	if x != nil {
		return x.MsgParam
	}
	return nil
}

func (x *SendMsgReq) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

type SendMsgResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	MsgId         int64                  `protobuf:"varint,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	SendTime      int64                  `protobuf:"varint,4,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMsgResp) Reset() {
	*x = SendMsgResp{}
	mi := &file_im_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgResp) ProtoMessage() {}

func (x *SendMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgResp.ProtoReflect.Descriptor instead.
func (*SendMsgResp) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{5}
}

func (x *SendMsgResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendMsgResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SendMsgResp) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *SendMsgResp) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

type PullMsgReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	LastMsgId     int64                  `protobuf:"varint,2,opt,name=last_msg_id,json=lastMsgId,proto3" json:"last_msg_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"` // max 50
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullMsgReq) Reset() {
	*x = PullMsgReq{}
	mi := &file_im_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMsgReq) ProtoMessage() {}

func (x *PullMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMsgReq.ProtoReflect.Descriptor instead.
func (*PullMsgReq) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{6}
}

func (x *PullMsgReq) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *PullMsgReq) GetLastMsgId() int64 {
	if x != nil {
		return x.LastMsgId
	}
	return 0
}

func (x *PullMsgReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PullMsgResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Messages      []*ImMessage           `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullMsgResp) Reset() {
	*x = PullMsgResp{}
	mi := &file_im_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMsgResp) ProtoMessage() {}

func (x *PullMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMsgResp.ProtoReflect.Descriptor instead.
func (*PullMsgResp) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{7}
}

func (x *PullMsgResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PullMsgResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *PullMsgResp) GetMessages() []*ImMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type AckMsgReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	MsgId         int64                  `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMsgReq) Reset() {
	*x = AckMsgReq{}
	mi := &file_im_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMsgReq) ProtoMessage() {}

func (x *AckMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMsgReq.ProtoReflect.Descriptor instead.
func (*AckMsgReq) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{8}
}

func (x *AckMsgReq) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *AckMsgReq) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

type HeartbeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReq) Reset() {
	*x = HeartbeatReq{}
	mi := &file_im_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReq) ProtoMessage() {}

func (x *HeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReq.ProtoReflect.Descriptor instead.
func (*HeartbeatReq) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatReq) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HeartbeatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResp) Reset() {
	*x = HeartbeatResp{}
	mi := &file_im_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResp) ProtoMessage() {}

func (x *HeartbeatResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResp.ProtoReflect.Descriptor instead.
func (*HeartbeatResp) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatResp) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type PushNewMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *ImMessage             `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushNewMessage) Reset() {
	*x = PushNewMessage{}
	mi := &file_im_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushNewMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushNewMessage) ProtoMessage() {}

func (x *PushNewMessage) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushNewMessage.ProtoReflect.Descriptor instead.
func (*PushNewMessage) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{11}
}

func (x *PushNewMessage) GetMessage() *ImMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

// Lightweight notification for world/system channels.
// Client should call PullMsg if chat UI is open.
type WorldNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	LatestSeq     int64                  `protobuf:"varint,2,opt,name=latest_seq,json=latestSeq,proto3" json:"latest_seq,omitempty"` // latest msg_id in this channel
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldNotify) Reset() {
	*x = WorldNotify{}
	mi := &file_im_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldNotify) ProtoMessage() {}

func (x *WorldNotify) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldNotify.ProtoReflect.Descriptor instead.
func (*WorldNotify) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{12}
}

func (x *WorldNotify) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *WorldNotify) GetLatestSeq() int64 {
	if x != nil {
		return x.LatestSeq
	}
	return 0
}

var File_im_proto protoreflect.FileDescriptor

const file_im_proto_rawDesc = "" +
	"\n" +
	"\bim.proto\x12\x05im.v1\"\xbc\x01\n" +
	"\n" +
	"SenderInfo\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x03R\bsenderId\x12\x1f\n" +
	"\vsender_name\x18\x02 \x01(\tR\n" +
	"senderName\x12*\n" +
	"\x11sender_head_image\x18\x03 \x01(\tR\x0fsenderHeadImage\x12\x1f\n" +
	"\vsender_rank\x18\x04 \x01(\x05R\n" +
	"senderRank\x12#\n" +
	"\ralliance_name\x18\x05 \x01(\tR\fallianceName\"\xc6\x02\n" +
	"\tImMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\x03R\x05msgId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x125\n" +
	"\fchannel_type\x18\x03 \x01(\x0e2\x12.im.v1.ChannelTypeR\vchannelType\x12)\n" +
	"\x06sender\x18\x04 \x01(\v2\x11.im.v1.SenderInfoR\x06sender\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12)\n" +
	"\bmsg_type\x18\x06 \x01(\x0e2\x0e.im.v1.MsgTypeR\amsgType\x12\x1b\n" +
	"\tmsg_param\x18\a \x03(\tR\bmsgParam\x12\x1b\n" +
	"\tsend_time\x18\b \x01(\x03R\bsendTime\x12\"\n" +
	"\rclient_msg_id\x18\t \x01(\tR\vclientMsgId\"\xd7\x01\n" +
	"\aAuthReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12V\n" +
	"\x14channel_last_msg_ids\x18\x03 \x03(\v2%.im.v1.AuthReq.ChannelLastMsgIdsEntryR\x11channelLastMsgIds\x1aD\n" +
	"\x16ChannelLastMsgIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"c\n" +
	"\bAuthResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x03R\x03uid\x12\x1f\n" +
	"\vserver_time\x18\x04 \x01(\x03R\n" +
	"serverTime\"\xe8\x01\n" +
	"\n" +
	"SendMsgReq\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x125\n" +
	"\fchannel_type\x18\x02 \x01(\x0e2\x12.im.v1.ChannelTypeR\vchannelType\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12)\n" +
	"\bmsg_type\x18\x04 \x01(\x0e2\x0e.im.v1.MsgTypeR\amsgType\x12\x1b\n" +
	"\tmsg_param\x18\x05 \x03(\tR\bmsgParam\x12\"\n" +
	"\rclient_msg_id\x18\x06 \x01(\tR\vclientMsgId\"g\n" +
	"\vSendMsgResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x15\n" +
	"\x06msg_id\x18\x03 \x01(\x03R\x05msgId\x12\x1b\n" +
	"\tsend_time\x18\x04 \x01(\x03R\bsendTime\"a\n" +
	"\n" +
	"PullMsgReq\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x1e\n" +
	"\vlast_msg_id\x18\x02 \x01(\x03R\tlastMsgId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"a\n" +
	"\vPullMsgResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12,\n" +
	"\bmessages\x18\x03 \x03(\v2\x10.im.v1.ImMessageR\bmessages\"A\n" +
	"\tAckMsgReq\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\x03R\x05msgId\",\n" +
	"\fHeartbeatReq\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"0\n" +
	"\rHeartbeatResp\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime\"<\n" +
	"\x0ePushNewMessage\x12*\n" +
	"\amessage\x18\x01 \x01(\v2\x10.im.v1.ImMessageR\amessage\"K\n" +
	"\vWorldNotify\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x1d\n" +
	"\n" +
	"latest_seq\x18\x02 \x01(\x03R\tlatestSeq*\xac\x01\n" +
	"\vChannelType\x12\x1c\n" +
	"\x18CHANNEL_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CHANNEL_TYPE_WORLD\x10\x01\x12\x19\n" +
	"\x15CHANNEL_TYPE_ALLIANCE\x10\x02\x12\x19\n" +
	"\x15CHANNEL_TYPE_ACTIVITY\x10\x03\x12\x18\n" +
	"\x14CHANNEL_TYPE_PRIVATE\x10\x04\x12\x17\n" +
	"\x13CHANNEL_TYPE_SYSTEM\x10\x05*\x86\x01\n" +
	"\aMsgType\x12\x18\n" +
	"\x14MSG_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rMSG_TYPE_TEXT\x10\x01\x12\x12\n" +
	"\x0eMSG_TYPE_IMAGE\x10\x02\x12\x12\n" +
	"\x0eMSG_TYPE_EMOJI\x10\x03\x12\x13\n" +
	"\x0fMSG_TYPE_SYSTEM\x10\x04\x12\x11\n" +
	"\rMSG_TYPE_LINK\x10\x05B\x10Z\x0egame-im/api/pbb\x06proto3"

var (
	file_im_proto_rawDescOnce sync.Once
	file_im_proto_rawDescData []byte
)

func file_im_proto_rawDescGZIP() []byte {
	file_im_proto_rawDescOnce.Do(func() {
		file_im_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_im_proto_rawDesc), len(file_im_proto_rawDesc)))
	})
	return file_im_proto_rawDescData
}

var file_im_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_im_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_im_proto_goTypes = []any{
	(ChannelType)(0),       // 0: im.v1.ChannelType
	(MsgType)(0),           // 1: im.v1.MsgType
	(*SenderInfo)(nil),     // 2: im.v1.SenderInfo
	(*ImMessage)(nil),      // 3: im.v1.ImMessage
	(*AuthReq)(nil),        // 4: im.v1.AuthReq
	(*AuthResp)(nil),       // 5: im.v1.AuthResp
	(*SendMsgReq)(nil),     // 6: im.v1.SendMsgReq
	(*SendMsgResp)(nil),    // 7: im.v1.SendMsgResp
	(*PullMsgReq)(nil),     // 8: im.v1.PullMsgReq
	(*PullMsgResp)(nil),    // 9: im.v1.PullMsgResp
	(*AckMsgReq)(nil),      // 10: im.v1.AckMsgReq
	(*HeartbeatReq)(nil),   // 11: im.v1.HeartbeatReq
	(*HeartbeatResp)(nil),  // 12: im.v1.HeartbeatResp
	(*PushNewMessage)(nil), // 13: im.v1.PushNewMessage
	(*WorldNotify)(nil),    // 14: im.v1.WorldNotify
	nil,                    // 15: im.v1.AuthReq.ChannelLastMsgIdsEntry
}
var file_im_proto_depIdxs = []int32{
	0,  // 0: im.v1.ImMessage.channel_type:type_name -> im.v1.ChannelType
	2,  // 1: im.v1.ImMessage.sender:type_name -> im.v1.SenderInfo
	1,  // 2: im.v1.ImMessage.msg_type:type_name -> im.v1.MsgType
	15, // 3: im.v1.AuthReq.channel_last_msg_ids:type_name -> im.v1.AuthReq.ChannelLastMsgIdsEntry
	0,  // 4: im.v1.SendMsgReq.channel_type:type_name -> im.v1.ChannelType
	1,  // 5: im.v1.SendMsgReq.msg_type:type_name -> im.v1.MsgType
	3,  // 6: im.v1.PullMsgResp.messages:type_name -> im.v1.ImMessage
	3,  // 7: im.v1.PushNewMessage.message:type_name -> im.v1.ImMessage
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_im_proto_init() }
func file_im_proto_init() {
	if File_im_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_im_proto_rawDesc), len(file_im_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_im_proto_goTypes,
		DependencyIndexes: file_im_proto_depIdxs,
		EnumInfos:         file_im_proto_enumTypes,
		MessageInfos:      file_im_proto_msgTypes,
	}.Build()
	File_im_proto = out.File
	file_im_proto_goTypes = nil
	file_im_proto_depIdxs = nil
}
